services:
  app:
    image: riks1233/alpine-gradle-openjdk17
    tty: true
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - ./app:/app
    networks:
      - spring-postgres
  db:
    hostname: ${DB_HOST}
    image: postgres:14.5
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    networks:
      - spring-postgres
    expose:
      - ${DB_PORT}
volumes:
  dbdata:
networks:
  spring-postgres:
