services:
  db:
    image: postgres:14.5
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - ${DB_PORT}:5432
  testdb:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=proxies_assignment_testdb
      - POSTGRES_USER=proxies_assignment_testdb_user
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
volumes:
  dbdata:
